using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public static class MessengerChatUIBuilder
{
    public static void AttachToPanel(GameObject messengerPanel, Sprite whiteSprite)
    {
        var font = TMP_Settings.defaultFontAsset;
        if (font == null)
        {
            Debug.LogError("TMP default font asset is missing. Use Window > TextMeshPro > Import TMP Essential Resources, then re-run Create Computer Desktop Canvas.");
            return;
        }
        var panelRt = messengerPanel.GetComponent<RectTransform>();
        var chatRoot = new GameObject("ChatRoot", typeof(RectTransform));
        Undo.RegisterCreatedObjectUndo(chatRoot, "Create ChatRoot");
        chatRoot.transform.SetParent(panelRt, false);
        var chatRootRt = chatRoot.GetComponent<RectTransform>();
        chatRootRt.anchorMin = new Vector2(0f, 0f);
        chatRootRt.anchorMax = new Vector2(1f, 1f);
        chatRootRt.offsetMin = new Vector2(16f, 16f);
        chatRootRt.offsetMax = new Vector2(-16f, -52f);
        var scrollGo = new GameObject("ChatScrollView", typeof(RectTransform), typeof(Image), typeof(ScrollRect));
        Undo.RegisterCreatedObjectUndo(scrollGo, "Create ChatScrollView");
        scrollGo.transform.SetParent(chatRoot.transform, false);
        var scrollRt = scrollGo.GetComponent<RectTransform>();
        scrollRt.anchorMin = new Vector2(0f, 0f);
        scrollRt.anchorMax = new Vector2(1f, 1f);
        scrollRt.offsetMin = new Vector2(0f, 56f);
        scrollRt.offsetMax = new Vector2(0f, 0f);
        var scrollBg = scrollGo.GetComponent<Image>();
        scrollBg.sprite = whiteSprite;
        scrollBg.type = Image.Type.Simple;
        scrollBg.color = new Color32(255, 255, 255, 40);
        var scrollRect = scrollGo.GetComponent<ScrollRect>();
        scrollRect.horizontal = false;
        scrollRect.movementType = ScrollRect.MovementType.Clamped;
        scrollRect.scrollSensitivity = 20f;
        var viewport = new GameObject("Viewport", typeof(RectTransform), typeof(Image), typeof(RectMask2D));
        Undo.RegisterCreatedObjectUndo(viewport, "Create Viewport");
        viewport.transform.SetParent(scrollGo.transform, false);
        var vpRt = viewport.GetComponent<RectTransform>();
        vpRt.anchorMin = Vector2.zero;
        vpRt.anchorMax = Vector2.one;
        vpRt.offsetMin = new Vector2(4f, 4f);
        vpRt.offsetMax = new Vector2(-4f, -4f);
        var vpImg = viewport.GetComponent<Image>();
        vpImg.sprite = whiteSprite;
        vpImg.type = Image.Type.Simple;
        vpImg.color = new Color32(255, 255, 255, 20);
        var content = new GameObject("Content", typeof(RectTransform), typeof(TextMeshProUGUI), typeof(ContentSizeFitter));
        Undo.RegisterCreatedObjectUndo(content, "Create Content");
        content.transform.SetParent(viewport.transform, false);
        var contentRt = content.GetComponent<RectTransform>();
        contentRt.anchorMin = new Vector2(0f, 1f);
        contentRt.anchorMax = new Vector2(1f, 1f);
        contentRt.pivot = new Vector2(0.5f, 1f);
        contentRt.anchoredPosition = Vector2.zero;
        contentRt.sizeDelta = new Vector2(0f, 0f);
        var fitter = content.GetComponent<ContentSizeFitter>();
        fitter.horizontalFit = ContentSizeFitter.FitMode.Unconstrained;
        fitter.verticalFit = ContentSizeFitter.FitMode.PreferredSize;
        var feedTmp = content.GetComponent<TextMeshProUGUI>();
        feedTmp.font = font;
        feedTmp.fontSize = 22;
        feedTmp.alignment = TextAlignmentOptions.TopLeft;
        feedTmp.color = new Color32(44, 62, 80, 255);
        feedTmp.text = string.Empty;
        feedTmp.enableWordWrapping = true;
        feedTmp.overflowMode = TextOverflowModes.Overflow;
        scrollRect.viewport = vpRt;
        scrollRect.content = contentRt;
        var inputRow = new GameObject("InputRow", typeof(RectTransform));
        Undo.RegisterCreatedObjectUndo(inputRow, "Create InputRow");
        inputRow.transform.SetParent(chatRoot.transform, false);
        var rowRt = inputRow.GetComponent<RectTransform>();
        rowRt.anchorMin = new Vector2(0f, 0f);
        rowRt.anchorMax = new Vector2(1f, 0f);
        rowRt.pivot = new Vector2(0.5f, 0f);
        rowRt.anchoredPosition = new Vector2(0f, 4f);
        rowRt.sizeDelta = new Vector2(0f, 52f);
        var inputGo = new GameObject("ChatInput", typeof(RectTransform), typeof(Image), typeof(TMP_InputField));
        Undo.RegisterCreatedObjectUndo(inputGo, "Create ChatInput");
        inputGo.transform.SetParent(inputRow.transform, false);
        var inputRt = inputGo.GetComponent<RectTransform>();
        inputRt.anchorMin = new Vector2(0f, 0f);
        inputRt.anchorMax = new Vector2(1f, 0f);
        inputRt.pivot = new Vector2(0f, 0f);
        inputRt.anchoredPosition = Vector2.zero;
        inputRt.sizeDelta = new Vector2(-112f, 46f);
        var inputBg = inputGo.GetComponent<Image>();
        inputBg.sprite = whiteSprite;
        inputBg.color = new Color32(255, 255, 255, 220);
        var tmpInput = inputGo.GetComponent<TMP_InputField>();
        var textArea = new GameObject("Text Area", typeof(RectTransform), typeof(RectMask2D));
        textArea.transform.SetParent(inputGo.transform, false);
        var taRt = textArea.GetComponent<RectTransform>();
        taRt.anchorMin = Vector2.zero;
        taRt.anchorMax = Vector2.one;
        taRt.offsetMin = new Vector2(8f, 6f);
        taRt.offsetMax = new Vector2(-8f, -6f);
        var placeholderGo = new GameObject("Placeholder", typeof(RectTransform), typeof(TextMeshProUGUI));
        placeholderGo.transform.SetParent(textArea.transform, false);
        StretchFull(placeholderGo.GetComponent<RectTransform>());
        var phTmp = placeholderGo.GetComponent<TextMeshProUGUI>();
        phTmp.font = font;
        phTmp.fontSize = 20;
        phTmp.color = new Color(0.4f, 0.4f, 0.4f, 0.65f);
        phTmp.text = "Type a message...";
        phTmp.alignment = TextAlignmentOptions.Left;
        var textGo = new GameObject("Text", typeof(RectTransform), typeof(TextMeshProUGUI));
        textGo.transform.SetParent(textArea.transform, false);
        StretchFull(textGo.GetComponent<RectTransform>());
        var inputTextTmp = textGo.GetComponent<TextMeshProUGUI>();
        inputTextTmp.font = font;
        inputTextTmp.fontSize = 20;
        inputTextTmp.color = new Color32(44, 62, 80, 255);
        inputTextTmp.alignment = TextAlignmentOptions.Left;
        inputTextTmp.enableWordWrapping = false;
        inputTextTmp.overflowMode = TextOverflowModes.Overflow;
        tmpInput.textViewport = taRt;
        tmpInput.textComponent = inputTextTmp;
        tmpInput.placeholder = phTmp;
        tmpInput.lineType = TMP_InputField.LineType.SingleLine;
        tmpInput.characterLimit = 512;
        var sendGo = new GameObject("BtnSend", typeof(RectTransform), typeof(Image), typeof(Button));
        Undo.RegisterCreatedObjectUndo(sendGo, "Create BtnSend");
        sendGo.transform.SetParent(inputRow.transform, false);
        var sendRt = sendGo.GetComponent<RectTransform>();
        sendRt.anchorMin = new Vector2(1f, 0f);
        sendRt.anchorMax = new Vector2(1f, 0f);
        sendRt.pivot = new Vector2(1f, 0f);
        sendRt.anchoredPosition = new Vector2(-2f, 0f);
        sendRt.sizeDelta = new Vector2(100f, 46f);
        var sendImg = sendGo.GetComponent<Image>();
        sendImg.sprite = whiteSprite;
        sendImg.color = new Color32(52, 152, 219, 255);
        var sendBtn = sendGo.GetComponent<Button>();
        sendBtn.targetGraphic = sendImg;
        var sendLabel = new GameObject("Label", typeof(RectTransform), typeof(TextMeshProUGUI));
        sendLabel.transform.SetParent(sendGo.transform, false);
        StretchFull(sendLabel.GetComponent<RectTransform>());
        var sendTmp = sendLabel.GetComponent<TextMeshProUGUI>();
        sendTmp.font = font;
        sendTmp.fontSize = 19;
        sendTmp.fontStyle = FontStyles.Bold;
        sendTmp.alignment = TextAlignmentOptions.Center;
        sendTmp.color = Color.white;
        sendTmp.text = "SEND";
        var managerGo = new GameObject("ChatManager", typeof(RectTransform), typeof(ChatManager));
        Undo.RegisterCreatedObjectUndo(managerGo, "Create ChatManager");
        managerGo.transform.SetParent(chatRoot.transform, false);
        var mgrRt = managerGo.GetComponent<RectTransform>();
        mgrRt.anchorMin = Vector2.zero;
        mgrRt.anchorMax = Vector2.one;
        mgrRt.offsetMin = Vector2.zero;
        mgrRt.offsetMax = Vector2.zero;
        var chatManager = managerGo.GetComponent<ChatManager>();
        var so = new SerializedObject(chatManager);
        so.FindProperty("chatScrollRect").objectReferenceValue = scrollRect;
        so.FindProperty("chatFeedText").objectReferenceValue = feedTmp;
        so.FindProperty("chatInputField").objectReferenceValue = tmpInput;
        so.FindProperty("sendButton").objectReferenceValue = sendBtn;
        so.ApplyModifiedProperties();
    }
    static void StretchFull(RectTransform rt)
    {
        rt.anchorMin = Vector2.zero;
        rt.anchorMax = Vector2.one;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;
        rt.localScale = Vector3.one;
    }
}
